export const APP_LOADED = "APP_LOADED";

export const CHECK_CONNECTION = "CHECK_CONNECTION";
export const CHECK_CONNECTION_SUCCESS = "CHECK_CONNECTION_SUCCESS";
export const CHECK_CONNECTION_FAILED = "CHECK_CONNECTION_FAILED";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const PROFILE_EDIT = "PROFILE_EDIT";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAILED = "PROFILE_EDIT_FAILED";

export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAILED = "CHANGE_EMAIL_FAILED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

export const LOGOUT = "LOGOUT";
